name: Harsimran Sidhu
title: Blogging for the future
description: Welcome to my blog!
tags:
  - blog
  - cybersecurity
  - jekyll
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: harsimransidhu770@gmail.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
